/* eslint-disable */
// @ts-nocheck
// biome-ignore lint: disable
// oxlint-disable
// ------
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399

export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    Button: typeof import('./../1-src/components/Button.vue')['default']
    ButtonCompliant: typeof import('./../1-src/components/button-compliant.vue')['default']
    GlobeBlack: typeof import('./../1-src/assets/svg/globe-black.svg')['default']
    GlobeWhite: typeof import('./../1-src/assets/svg/globe-white.svg')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
  }
}
